spring:
  application:
    name: servicio-productos
  datasource:
    url: jdbc:mysql://msmysql8:3306/db_springboot_cloud?serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Docker76--
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 10000 #10s
      idle-timeout: 300000 #5m
      max-lifetime: 600000 #10m
      initialization-fail-timeout: -1
      validation-timeout: 1000 #1s
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
server:
  port: ${PORT:0}
eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    appname: servicio-productos
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  level:
    sql: info
  file:
    path: /app/logs

