spring:
  application:
    name: servicio-productos
  datasource:
    url: jdbc:mysql://MSmysql8:3306/db_springboot_cloud?serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Docker76--
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl: 
      defaultZone: http://eureka-server:8761/eureka/
logging:
  level:
    sql: info
  file:
    path: /app/logs